# It is Bhojpur GUI client's TOML document, which shows most of its features.

# Simple key/value with a string.
title = "Bhojpur GUI \U0001F60A"

desc = """
An example of Bhojpur GUI's client configuration in TOML document format. \
"""

log = "bhojpur_gui_client_log.txt"

# Array with integers and floats in the various allowed formats.
integers = [42, 0x42, 0o42, 0b0110]
floats   = [1.42, 1e-02]

# Array with supported datetime formats.
times = [
	2018-03-26T15:16:17+01:00,  # datetime with timezone.
	2018-03-26T15:16:17Z,       # UTC datetime.
	2018-03-26T15:16:17,        # local datetime.
	2018-03-26,                 # local date.
	15:16:17,                   # local time.
]

# Custom Unmarshal.
duration = ["4m49s", "8m03s", "1231h15m55s"]

# Table with inline tables.
distros = [
	{name = "Arch Linux", packages = "pacman"},
	{name = "Void Linux", packages = "xbps"},
	{name = "Debian",     packages = "apt"},
]

# Create new table; note the "servers" table is created implicitly.
[servers.dev]
	ip        = '127.0.0.1'
	hostname  = 'localhost'
	enabled   = true
[servers.alpha]
	# You can indent as you please, tabs or spaces.
	ip        = '10.0.0.1'
	hostname  = 'server1'
	enabled   = false
[servers.beta]
	ip        = '10.0.0.2'
	hostname  = 'server2'
	enabled   = false

# Start a new table array; note that the "characters" table is created implicitly.
[[characters.star-trek]]
	name = "James Kirk"
	rank = "Captain"
[[characters.star-trek]]
	name = "Spock"
	rank = "Science officer"

[undecoded] # To show the MetaData.Undecoded() feature.
	key = "This table intentionally left undecoded"