// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GuiUIClient is the client API for GuiUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuiUIClient interface {
	// ListEngineSpecs returns a list of GUI Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (GuiUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type guiUIClient struct {
	cc grpc.ClientConnInterface
}

func NewGuiUIClient(cc grpc.ClientConnInterface) GuiUIClient {
	return &guiUIClient{cc}
}

func (c *guiUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (GuiUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &GuiUI_ServiceDesc.Streams[0], "/v1.GuiUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &guiUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GuiUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type guiUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *guiUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *guiUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.GuiUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuiUIServer is the server API for GuiUI service.
// All implementations must embed UnimplementedGuiUIServer
// for forward compatibility
type GuiUIServer interface {
	// ListEngineSpecs returns a list of GUI Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, GuiUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedGuiUIServer()
}

// UnimplementedGuiUIServer must be embedded to have forward compatible implementations.
type UnimplementedGuiUIServer struct {
}

func (UnimplementedGuiUIServer) ListEngineSpecs(*ListEngineSpecsRequest, GuiUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedGuiUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedGuiUIServer) mustEmbedUnimplementedGuiUIServer() {}

// UnsafeGuiUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuiUIServer will
// result in compilation errors.
type UnsafeGuiUIServer interface {
	mustEmbedUnimplementedGuiUIServer()
}

func RegisterGuiUIServer(s grpc.ServiceRegistrar, srv GuiUIServer) {
	s.RegisterService(&GuiUI_ServiceDesc, srv)
}

func _GuiUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuiUIServer).ListEngineSpecs(m, &guiUIListEngineSpecsServer{stream})
}

type GuiUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type guiUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *guiUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GuiUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuiUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GuiUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuiUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuiUI_ServiceDesc is the grpc.ServiceDesc for GuiUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuiUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GuiUI",
	HandlerType: (*GuiUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _GuiUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _GuiUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gui-ui.proto",
}
